export const DATA = {
  // El problema
  totalLeadsActivos: 4552,
  leadsSinVisita: 4455,
  leadsSelfServiceSinAtencion: 3636,
  tasaConversionActual: 2.13,
  leadsConVisita: 97,
  tiempoPrimeraRespuesta: '26.5 horas',
  tiempoPrimeraRespuestaHrs: 26.5,
  leadsNuevosPorSemana: 58,
  leadsAtendidosPorSemana: 9,

  // El inventario
  spotsPublicosActivos: 5554,
  leadsConCriteriosCompletos: 4314,
  porcentajeCriteriosCompletos: 94.8,

  // Brokers
  brokersRegistrados: 5540,
  brokersActivos: 42,
  porcentajeBrokersActivos: 0.76,
  ratioTopVsBottom: 27,

  // El impacto con Match Engine
  tiempoConAgente: '47 segundos',
  tiempoConAgenteSeg: 47,
  factorMejora: 113,
  visitasAdicionalesMes1: 363,
  pipelineRecuperadoMes1: '$2.7M MXN',
  pipelineRecuperadoMes1Num: 2.7,
  objetivoConversionMes1: 8,

  leadsDemo: [
    {
      id: 8412,
      nombre: 'Ana G.',
      empresa: 'Grupo Corporativo Torres',
      busca: 'Oficina corporativa',
      area: '150 – 250 m²',
      zona: 'Polanco / Lomas de Chapultepec',
      presupuesto: '$90,000 MXN/mes',
      telefono: '+52 55 •••• ••••',
      origen: 'Self-service',
      horasSinRespuesta: 18,
      criteriosCompletos: true,
    },
    {
      id: 8301,
      nombre: 'Logística NORTE S.A.',
      empresa: 'Logística NORTE S.A. de C.V.',
      busca: 'Bodega industrial',
      area: '2,500 – 4,000 m²',
      zona: 'Vallejo / Azcapotzalco',
      presupuesto: '$180,000 MXN/mes',
      telefono: '+52 55 •••• ••••',
      origen: 'Self-service',
      horasSinRespuesta: 72,
      criteriosCompletos: true,
    },
    {
      id: 8289,
      nombre: 'Retail Express',
      empresa: 'Retail Express México',
      busca: 'Local comercial',
      area: '100 – 150 m²',
      zona: 'Condesa / Roma Norte',
      presupuesto: '$45,000 MXN/mes',
      telefono: '+52 55 •••• ••••',
      origen: 'Self-service',
      horasSinRespuesta: 6,
      criteriosCompletos: true,
    },
    {
      id: 8255,
      nombre: 'Manufactura del Valle',
      empresa: 'Manufactura del Valle SAPI',
      busca: 'Bodega ligera',
      area: '800 – 1,200 m²',
      zona: 'Tlalnepantla / Naucalpan',
      presupuesto: '$120,000 MXN/mes',
      telefono: '+52 55 •••• ••••',
      origen: 'Self-service',
      horasSinRespuesta: 41,
      criteriosCompletos: true,
    },
    {
      id: 8219,
      nombre: 'Fintech Mx',
      empresa: 'Fintech Mx Holdings',
      busca: 'Oficina coworking',
      area: '60 – 100 m²',
      zona: 'Reforma / Juárez',
      presupuesto: '$32,000 MXN/mes',
      telefono: '+52 55 •••• ••••',
      origen: 'Self-service',
      horasSinRespuesta: 8,
      criteriosCompletos: true,
    },
  ],

  espaciosMatch: [
    {
      id: 'S-4421',
      nombre: 'Torre Corporativa Masaryk',
      piso: 'Piso 8',
      area: 210,
      precio: 87500,
      zona: 'Polanco',
      clase: 'A',
      amenidades: ['Estacionamiento', 'Elevador', 'Aire acondicionado', 'Seguridad 24/7'],
      disponible: true,
      diasDisponible: 0,
      score: 94,
    },
    {
      id: 'S-3819',
      nombre: 'Lomas Business Park',
      piso: 'Suite Ejecutiva',
      area: 185,
      precio: 82000,
      zona: 'Lomas de Chapultepec',
      clase: 'A',
      amenidades: ['Vista panorámica', 'Estacionamiento', 'Sala de juntas'],
      disponible: true,
      diasDisponible: 0,
      score: 89,
    },
    {
      id: 'S-4108',
      nombre: 'Antara Office Center',
      piso: 'Planta libre',
      area: 240,
      precio: 89000,
      zona: 'Polanco',
      clase: 'B+',
      amenidades: ['Planta libre', 'Estacionamiento', 'Food court'],
      disponible: false,
      diasDisponible: 15,
      score: 81,
    },
  ],
} as const

export type Lead = (typeof DATA.leadsDemo)[number]
export type Espacio = (typeof DATA.espaciosMatch)[number]

export const SCREENS = [
  { id: 0, name: 'Hero', label: 'Intro' },
  { id: 1, name: 'Problema', label: 'Dashboard' },
  { id: 2, name: 'Radar', label: 'Lead detectado' },
  { id: 3, name: 'Match', label: 'Matching' },
  { id: 4, name: 'Ficha', label: 'Ficha' },
  { id: 5, name: 'WhatsApp', label: 'Conversación' },
  { id: 6, name: 'Confirma', label: 'Confirmación' },
  { id: 7, name: 'Impacto', label: 'Resultados' },
] as const

export const FUNNEL_STEPS = [
  { value: 5554, label: 'Total inventario activo', filter: 'Inventario' },
  { value: 847, label: 'Filtro por zona (Polanco / Lomas)', filter: 'Zona' },
  { value: 124, label: 'Filtro por área (150 – 250 m²)', filter: 'Área' },
  { value: 38, label: 'Filtro por presupuesto (≤ $90K)', filter: 'Presupuesto' },
  { value: 3, label: 'Match semántico final', filter: 'Match' },
] as const
